ALTER TABLE peers ADD COLUMN alert_on_connect INTEGER NOT NULL DEFAULT 0;
ALTER TABLE peers ADD COLUMN alert_on_disconnect INTEGER NOT NULL DEFAULT 0;
ALTER TABLE peers ADD COLUMN alert_emails TEXT NOT NULL DEFAULT '';
